dist: xenial
sudo: required

language: node_js
node_js:
- "8.11.3"

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
- sudo apt-get install -qq g++-8
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
- git clone https://github.com/emilydolson/Empirical ../Empirical -b memic_merge
- git clone https://github.com/emscripten-core/emsdk.git && cd emsdk && git pull && ./emsdk install 1.38.48 && ./emsdk activate 1.38.48 && . ./emsdk_env.sh && cd ..

script:
- make test

after_success:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- cd web
- git init
- git remote add origin https://${GH_TOKEN}@github.com/mmore500/config-panel-app.git > /dev/null 2>&1
- git checkout -b gh-pages
- git add .
- git commit --message "Travis build ${TRAVIS_BUILD_NUMBER}"
- test ${TRAVIS_BRANCH} = "master" && git push --force --quiet origin gh-pages
env:
  global:
    secure: x/hVsId4l6X/ytnOpC4so/kaOFTvIFzmww3UrTQrrH9PgYaYTihrWjCi+VMPQpTmAC0NU+snMt1rFOP0f/DXMt90YfxM3XtJ3OWp8k36TEJCg85s5PDTaWn12HOTZkWH2Ln8cdHwJdJfcM1a920o5U4JgSp4HH20KvA6fz5RK4ZO0TLai8CbaJNf1/44EXwID0NqgjR+asrlaAPOhEG+1Zxgp2CXecL3GTBxJoL7JcVrjtwoJrOYjfq2VD8eGb3E4HNco350JqWnI401WOxT/1t2fRu1AHJ8giLFw53oUkixXc2NGju2aG147p78G5QB3mqsO7T3+nBZKDTf4UO6d90u/6ypcwZS9CtvnnV34h3rcA9M9bSmU4FUgnhhrPezB/a7FlmowEQ7veSktBiMEjNbxzNRM7EctzHGrTIj86ljpFetyjhDY3N3MVMMkv2Sg4pMq6PxALiqesFTxrvTtygAhnwDc/FFSksfIx1/TkoXcsWlPP7LoaqBEpUFZi+xIaDs+nVFrte4TqOpkLl12Xj4MO/3tBv7dyIdMJ28H4KKK6iiyb52pKzyAiupFzfCU3vA5Lo4PWMBwEM5TDEY4gvGibusHCuWAXrJWVPCnXptLVJWCHkBj8M79eoneKiPplnIUmqabBLX0Y2SqYAnCkF1Jo69OIJ7EPmYFWqYVDI=
